default: &default
  adapter: mysql2
  pool: 3
  username: qiqi
  password: bfN4nUQwGeajdKr8gtQXvjJEtbuymPfV!!
  timeout: 5000
  host: www.pachong.com
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci



development:
  <<: *default
  database: blog_development


production:
  <<: *default
  database: blog_production

